swagger: '2.0'
info:
  description: ''
  version: ''
  title: ''
host: __hostname__
schemes:
  - http
  - https
basePath: /apiUi/api
paths:
  /logs:
    delete:
      summary: removes list of logitems from Ui
      description: ''
      operationId: zzClearLogs
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
      responses:
        '200':
          decsription: Success response
  /logs/fetchfromremoteserver:
    post:
      summary: fetches list of logitems from apiUi in the cloud
      description: ''
      operationId: zzFetchLogsFromRemoteServer
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
      responses:
        '200':
          decsription: Success response
  /logs/snapshot:
    post:
      summary: summary
      description: ''
      operationId: zzTakeSnapshot
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: body
          in: body
          decsription: ''
          required: 'true'
          schema:
            $ref: '#/definitions/createSnapshotReq'
      responses:
        '200':
          decsription: Success response
  /snapshot/checkregression:
    post:
      summary: summary
      description: ''
      operationId: zzCheckSnapshotRegression
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: body
          in: body
          decsription: ''
          required: 'true'
          schema:
            $ref: '#/definitions/checkRegressionReq'
      responses:
        '200':
          decsription: Success response
          schema:
            $ref: '#/definitions/checkRegresssionRpy'
  /snapshots:
    delete:
      summary: removes entries from the list of snapshots
      description:
        removes entries from the list of snapshots.
        The snapshots are not removed from your filesystem.
      operationId: zzClearSnapshots
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
      responses:
        '200':
          decsription: Success response
    get:
      summary: retrieves list of snapshots (in project folder)
      description:
        retrieves list of snapshots.
        Scans project folder for snapshots.
      operationId: zzListSnapshots
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
      responses:
        '200':
          description: Success response
          schema:
            $ref: '#/definitions/listOfSnapshots'
  /executeScript:
    post:
      summary: summary
      description: ''
      operationId: zzExecuteScript
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: body
          in: body
          decsription: ''
          required: 'true'
          schema:
            $ref: '#/definitions/executeScriptReq'
      responses:
        '200':
          decsription: Success response
          schema:
            $ref: '#/definitions/executeScriptRpy'

  /operations/{operationAlias}/delay:
    get:
      summary: gets delay as set for operation
      description:
        delays are random between min and max value.
      operationId: zzGetOperationDelay
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: operationAlias
          in: path
          type: string
      responses:
        '200':
          description: Success response
          schema:
            $ref: '#/definitions/operationDelaySetting'
    put:
      summary: set delay to random between min and max milliseconds
      description:
        Set the extra time that  apiUi should wait before sending response.
        The snapshots are not removed from your filesystem.
      operationId: zzSetOperationDelay
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: operationAlias
          in: path
          type: string
        - name: body
          in: body
          schema:
            $ref: '#/definitions/operationDelaySetting'
      responses:
        '200':
          description: Success response
  /refresh:
    post:
      summary: reloads project from project definition as at is on the server filesystem
      description: ''
      operationId: zzRefresh
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: body
          in: body
          decsription: ''
          required: 'true'
          schema:
            $ref: '#/definitions/refreshReq'
      responses:
        '202':
          decsription: Success response
          schema:
            $ref: '#/definitions/refreshRpy'
  /regressionReport:
    post:
      summary: summary
      description: ''
      operationId: zzRegressionReport
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: body
          in: body
          decsription: ''
          required: 'true'
          schema:
            $ref: '#/definitions/regressionReportReq'
      responses:
        '200':
          decsription: Success response
          schema:
            $ref: '#/definitions/regressionReportRpy'
  /resetEnvVar:
    post:
      summary: summary
      description: ''
      operationId: zzResetEnvVar
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: body
          in: body
          decsription: ''
          required: 'true'
          schema:
            $ref: '#/definitions/resetEnvVarReq'
      responses:
        '200':
          decsription: Success response
          schema:
            $ref: '#/definitions/resetEnvVarRpy'
  /resetEnvVars:
    post:
      summary: summary
      description: ''
      operationId: zzResetEnvVars
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: body
          in: body
          decsription: ''
          required: 'true'
          schema:
            $ref: '#/definitions/resetEnvVarsReq'
      responses:
        '200':
          decsription: Success response
          schema:
            $ref: '#/definitions/resetEnvVarsRpy'
  /setContext:
    post:
      summary: summary
      description: ''
      operationId: zzSetContext
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: body
          in: body
          decsription: ''
          required: 'true'
          schema:
            $ref: '#/definitions/setContextReq'
      responses:
        '200':
          decsription: Success response
          schema:
            $ref: '#/definitions/setContextRpy'
  /setEnvVar:
    post:
      summary: summary
      description: ''
      operationId: zzSetEnvVar
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: body
          in: body
          decsription: ''
          required: 'true'
          schema:
            $ref: '#/definitions/setEnvVarReq'
      responses:
        '200':
          decsription: Success response
          schema:
            $ref: '#/definitions/setEnvVarRpy'
  /shutDown:
    post:
      summary: summary
      description: ''
      operationId: zzShutDown
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: body
          in: body
          decsription: ''
          required: 'true'
          schema:
            $ref: '#/definitions/shutDownReq'
      responses:
        '200':
          decsription: Success response
          schema:
            $ref: '#/definitions/shutDownRpy'
  /versionInfo:
    post:
      summary: get apiUi version information
      description: ''
      operationId: zzVersionInfo
      consumes:
        - application/json
      produces:
        - application/json
      responses:
        '200':
          decsription: Success response
          schema:
            $ref: '#/definitions/versionInfo'
definitions:
  checkRegressionReq:
    type: object
    properties:
      name:
        type: string
  checkRegresssionRpy:
    type: object
    properties:
      result:
        type: string
  createSnapshotReq:
    type: object
    properties:
      name:
        type: string
  executeScriptReq:
    type: object
    properties:
      name:
        type: string
  executeScriptRpy:
    type: string
  operationDelaySetting:
    type: object
    properties:
      randomBetween:
       type: object
       properties:
         min:
          type: integer
         max:
          type: integer
  refreshReq:
    type: string
  refreshRpy:
    type: string
  regressionReportReq:
    type: object
    properties:
      referenceFileName:
        type: string
  regressionReportRpy:
    type: object
    properties:
      Header:
        type: object
        properties:
          differencesFound:
            type: boolean
          referenceLogFileName:
            type: string
          Created:
            type: dateTime
      Body:
        type: object
        properties:
          Detail:
            type: array
            items:
              type: object
              properties:
                messageTimestamp:
                  type: dateTime
                Service:
                  type: string
                Operation:
                  type: string
                Message:
                  type: string
                Correlation:
                  type: string
                Type:
                  type: string
                Items:
                  type: object
                  properties:
                    Item:
                      type: array
                      items:
                        type: object
                        properties:
                          Tag:
                            type: string
                          Type:
                            type: string
                          currentValue:
                            type: string
                          referenceValue:
                            type: string
  resetEnvVarReq:
    type: object
    properties:
      name:
        type: string
  resetEnvVarRpy:
    type: string
  resetEnvVarsReq:
    type: object
    properties:
      regularExpression:
        type: string
  resetEnvVarsRpy:
    type: string
  setContextReq:
    type: object
    properties:
      name:
        type: string
  setContextRpy:
    type: object
    properties:
      previousContext:
        type: object
        properties:
          name:
            type: string
  setEnvVarReq:
    type: object
    properties:
      name:
        type: string
      value:
        type: string
  setEnvVarRpy:
    type: string
  shutDownReq:
    type: string
  shutDownRpy:
    type: string
  unexpectedValuesReportReq:
    type: string
  unexpectedValuesReportRpy:
    type: object
    properties:
      Header:
        type: object
        properties:
          unexpectedValuesFound:
            type: boolean
          Created:
            type: dateTime
      Body:
        type: object
        properties:
          Detail:
            type: array
            items:
              type: object
              properties:
                messageTimestamp:
                  type: dateTime
                Service:
                  type: string
                Operation:
                  type: string
                Message:
                  type: string
                Correlation:
                  type: string
                Type:
                  type: string
                Items:
                  type: object
                  properties:
                    Item:
                      type: array
                      items:
                        type: object
                        properties:
                          Tag:
                            type: string
                          Type:
                            type: string
                          currentValue:
                            type: string
                          referenceValue:
                            type: string
  listOfSnapshots:
    type: object
    properties:
      snapshots:
        type: array
        items:
          type: object
          properties:
            name:
              type: string
            createdOn:
              type: dateTime
  versionInfo:
    type: object
    properties:
      version:
        type: string
