  gsIdVersionMajor = 10;
  {$NODEFINE gsIdVersionMajor}
  gsIdVersionMinor = 6;
  {$NODEFINE gsIdVersionMinor}
  gsIdVersionRelease = 2;
  {$NODEFINE gsIdVersionRelease}
  gsIdVersionBuild = 5475;
  {$NODEFINE gsIdVersionBuild}

  (*$HPPEMIT '#define gsIdVersionMajor 10'*)
  (*$HPPEMIT '#define gsIdVersionMinor 6'*)
  (*$HPPEMIT '#define gsIdVersionRelease 2'*)
  (*$HPPEMIT '#define gsIdVersionBuild 5475'*)
  (*$HPPEMIT ''*)

  gsIdVersion = '10.6.2.5475'; {do not localize}
  gsIdProductName = 'Indy';  {do not localize}
  gsIdProductVersion = '10.6.2'; {do not localize}
