---
swagger: '2.0'
definitions:
      Activity: 
          type: object
          properties: 
            TypeCode: 
              type: string
              maxLength: 30
            StatusCode: 
              type: string
              maxLength: 30
            TaskReference: 
              type: string
              maxLength: 30
            Description: 
              type: string
              maxLength: 150
            Comment: 
              type: string
              maxLength: 1500
            StartDate: 
              type: string
              format: "date-time"
            EndDate: 
              type: string
              format: "date-time"
            PlannedEndDate: 
              type: string
              format: "date-time"
          required: 
            - TypeCode
            - Description
