---
swagger: '2.0'
info:
  description: ''
  version: ''
  title: ''
host: distributie-api.intern.rabobank.nl
basePath: "/test/bhpq"
schemes:
- https
paths:
  "/testparams/{pathparam}":
    post:
      summary: test passing params
      description: ''
      operationId: bhpq1
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - name: pathparam
        in: path
        description: ''
        required: true
        type: string
      - name: headerparam
        in: header
        description: ''
        required: true
        type: string
      - name: queryparam
        in: query
        description: ''
        required: true
        type: string
      - name: body
        in: body
        description: ''
        required: true
        schema:
          "$ref": "#/definitions/bhpq_req"
      responses:
        '200':
          description: Success response
          schema:
            "$ref": "#/definitions/bhpq_rpy"
definitions:
  bhpq_req: 
    type: object
    properties: 
      bodyparam: 
        type: string
    required: 
      - bodyparam
  bhpq_rpy: 
    type: object
    properties: 
      bodyparam: 
        type: string
      headerparam: 
        type: string
      pathparam: 
        type: string
      queryparam: 
        type: string
      noparam:
        type: string
