---
swagger: '2.0'
info:
  description: ''
  version: ''
  title: ''
host: distributie-api.intern.rabobank.nl
basePath: "/crmi/api/klant"
schemes:
- https
paths:
  "/createactivities/3/{type}":
    post:
      summary: summary
      description: ''
      operationId: CreateActivities
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - name: type
        in: path
        description: ''
        required: true
        type: string
      - name: apiheader
        in: header
        description: ''
        required: true
        type: string
      - name: queryparam
        in: query
        description: ''
        required: true
        type: string
      - name: body
        in: body
        description: ''
        required: true
        schema:
          "$ref": "#/definitions/CreateActivities_Req"
      responses:
        '200':
          description: Success response
          schema:
            "$ref": "#/definitions/CreateActivities_Rpy"
definitions:
  CreateActivities_Req: 
    type: object
    properties: 
      Contact: 
        type: object
        properties: 
          ContactId: 
            type: string
            maxLength: 15
        required: 
          - ContactId
      Department: 
        type: object
        properties: 
          DepId: 
            type: number
            format: float
        required: 
          - BankCode
      ServiceRequest: 
        type: object
        properties: 
          Reference: 
            type: string
            maxLength: 30
        required: 
          - Reference
      Activity: 
          type: object
          properties: 
            TypeCode: 
              type: string
              maxLength: 30
            StatusCode: 
              type: string
              maxLength: 30
            TaskReference: 
              type: string
              maxLength: 30
            Description: 
              type: string
              maxLength: 150
            Comment: 
              type: string
              maxLength: 1500
            StartDate: 
              type: string
              format: "date-time"
            EndDate: 
              type: string
              format: "date-time"
            PlannedEndDate: 
              type: string
              format: "date-time"
          required: 
            - TypeCode
            - Description
        required: 
          - Activity
    required: 
      - Contact
      - Department
      - Activity
  CreateActivities_Rpy: 
    type: object
    properties: 
      ListOfActivities: 
        type: object
        properties: 
          Activity: 
            type: array
            items: 
              type: object
              properties: 
                TaskReference: 
                  type: string
                  maxLength: 30
                Document: 
                  type: object
                  properties: 
                    StorageStatus: 
                      type: string
                      maxLength: 20
                  required: 
                    - StorageStatus
              required: 
                - TaskReference
        required: 
          - Activity
    required: 
      - ListOfActivities
  SOAPFault: 
    type: object
    properties: 
      applicationfaultcode: 
        type: string
      applicationfaulttext: 
        type: string
    required: 
      - applicationfaultcode
      - applicationfaulttext
