---
swagger: '2.0'
info:
  description: ''
  version: ''
  title: ''
host: distributie-api.intern.rabobank.nl
basePath: "/crmi/api/klant"
schemes:
- https
paths:
  "/createactivities/3/{pathParam}":
    post:
      summary: summary
      description: ''
      operationId: CreateActivities
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - name: pathParam
        in: path
        description: ''
        required: true
        type: string
      - name: headerParam
        in: header
        description: ''
        required: true
        type: string
      - name: queryParam
        in: query
        description: ''
        required: true
        type: string
      - name: body
        in: body
        description: ''
        required: true
        schema:
          "$ref": "#/definitions/CreateActivities_Req"
      responses:
        '200':
          description: Success response
          schema:
            "$ref": "#/definitions/CreateActivities_Rpy"
definitions:
  CreateActivities_Req: 
    type: object
    properties: 
      Contact: 
        type: object
        properties: 
          bodyParam: 
            type: string
            maxLength: 15
        required: 
          - bodyParam
      Department: 
        type: object
        properties: 
          DepId: 
            type: number
            format: float
        required: 
          - BankCode
      ServiceRequest: 
        type: object
        properties: 
          Reference: 
            type: string
            maxLength: 30
        required: 
          - Reference
      Activity:
         '$ref': 'activity.yml#/definitions/Activity'
    required: 
      - Contact
      - Department
      - Activity
  CreateActivities_Rpy: 
    type: object
    properties:
      fromPathParam:    
        type: string
      fromHeaderParam:    
        type: string
      fromQueryParam:    
        type: string
      fromBodyParam:    
        type: string
      ListOfActivities: 
        type: object
        properties: 
          Activity: 
            type: array
            items: 
              type: object
              properties: 
                TaskReference: 
                  type: string
                  maxLength: 30
                Document: 
                  type: object
                  properties: 
                    StorageStatus: 
                      type: string
                      enum:
                      - Archived
                      - Compressed
                      maxLength: 20
                  required: 
                    - StorageStatus
              required: 
                - TaskReference
        required: 
          - Activity
    required: 
      - ListOfActivities
  SOAPFault: 
    type: object
    properties: 
      applicationfaultcode: 
        type: string
      applicationfaulttext: 
        type: string
    required: 
      - applicationfaultcode
      - applicationfaulttext
