<definitions 
 xmlns="http://schemas.xmlsoap.org/wsdl/" 
 xmlns:xsd="http://www.w3.org/2001/XMLSchema" 
 xmlns:req="http://apiUiMenu.xsd" 
 xmlns:rpy="http://apiUiMenu.xsd"  
 xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" 
 xmlns:client="http://www.rabobank.nl/CRM/CRMI/apiUiMenu"  
 xmlns:ns3="http://schemas.xmlsoap.org/soap/encoding/" 
 name="apiUiMenu" 
 targetNamespace="http://www.rabobank.nl/CRM/CRMI/apiUiMenu"
>
	<types>
		<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
			<xsd:import namespace="http://apiUiMenu.xsd" schemaLocation="apiUiMenu.xsd"/>
		</xsd:schema>
	</types>
	<message name="apiUiMenuResponseMessage">
		<part name="payload" element="rpy:Menu"/>
	</message>
	<message name="apiUiMenuRequestMessage">
		<part name="payload" element="req:Menu"/>
	</message>
	<portType name="apiUiMenu">
		<operation name="process">
			<input message="client:apiUiMenuRequestMessage"/>
			<output message="client:apiUiMenuResponseMessage"/>
		</operation>
	</portType>
	<binding name="apiUiMenuBinding" type="client:apiUiMenu">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
		<operation name="process">
			<soap:operation soapAction="process" style="document"/>
			<input>
				<soap:body use="literal"/>
			</input>
			<output>
				<soap:body use="literal"/>
			</output>
		</operation>
	</binding>
	<service name="apiUiMenu">
		<port name="apiUiMenuPort" binding="client:apiUiMenuBinding">
			<soap:address location="http://ToBeReplacedByServer:7777/orabpel/default/apiUiMenu/2/"/>
		</port>
	</service>
</definitions>
